MODEL:
  TYPE: Dtransformer
  NAME: simmim_finetune
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 6, 12, 24, 48 ]
    WINDOW_SIZE: 14
  LABEL_SMOOTHING: 0.0
DATA:
  IMG_SIZE: 224
  MASK_PATCH_SIZE: 4
  MASK_RATIO: 0.6
  DATASET: huston13-18
TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 20
  BASE_LR: 1.25e-3
  WARMUP_LR: 2.5e-7
  MIN_LR: 2.5e-7
  WEIGHT_DECAY: 0.05
  LAYER_DECAY: 0.7
PRINT_FREQ: 100
SAVE_FREQ: 5
TAG: simmim_finetune__Dtransformer_finetune
IS_HSI: TRUE
IS_DIST: False
AUG:
  MIXUP: 0.0