MODEL:
  TYPE: Dtransformer
  NAME: simmim_pretrain
  DROP_PATH_RATE: 0.0
  Dtransformer:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 6
DATA:
  IMG_SIZE: 192
  MASK_PATCH_SIZE: 4
  MASK_RATIO: 0.6
TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 10
  BASE_LR: 1e-6
  WARMUP_LR: 1e-6
  MIN_LR: 1e-5
  WEIGHT_DECAY: 0.05
PRINT_FREQ: 100
SAVE_FREQ: 5
TAG: simmim_Dtransformer_pretrain
